scenarios: "C:\\Users\\jjaro\\PycharmProjects\\selenium-generator\\scenarios\\"
data: "C:\\Users\\jjaro\\PycharmProjects\\selenium-generator\\data\\"
pages: "C:\\Users\\jjaro\\PycharmProjects\\selenium-generator\\pages\\"
report:
  combine_reports: true
  report_name: "TestReport"
screenshots: ""
driver:
  type: ["chrome", "firefox"]
  headless: false
  remote: false
tags: ["regression"]

