scenarios: "../scenarios"
data: "../data"
pages: "../pages"

report:
  screenshots: true
  clean: true
  params:
    output: "../report"
    combine_reports: true
    report_name: "TestReport"
    report_title: "Sample Report"

tags: []

drivers:
  chrome:
    remote: false
    version: "80.0.3987.106"

  firefox:
    remote: false
