scenarios: "D:\\PyCharmProjects\\selenium-generator\\scenarios\\"
data: "D:\\PycharmProjects\\selenium-generator\\data\\"
pages: "D:\\PycharmProjects\\selenium-generator\\pages\\"

report:
  screenshots: true
  clean: true
  params:
    output: "D:\\PycharmProjects\\selenium-generator\\report"
    combine_reports: true
    report_name: "TestReport"
    report_title: "Sample Report"

tags: ["aaa"]

driver:
  type: ["chrome", "firefox"]
  headless: false
  remote: false
  params:
    version: "81"


