scenarios: "scenarios"
data: "data"
pages: "pages"

report:
    screenshots: true
    clean: true
    params:
        output: "./reports/"
        report_name: "TestReport"
        report_title: "Test results"

tags: []

drivers:
  chrome:
    remote: false
    allowed: true

  firefox:
    remote: false
    allowed: true